name: SteamMetrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
            filename: metrics.plugin.steam.svg
            token: NOT_NEEDED
            base: ""
            plugin_introduction: yes
            plugin_introduction_title: yes
            plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
            plugin_steam: yes
            plugin_steam_user: "76561198160602739"
            plugin_steam_sections: recently-played
            plugin_steam_achievements_limit: 0
